### ISSUE TITLE
[Question] How are`AARCH64_MOVW_UABS_G*` relocations handled?

### ISSUE THREAD

**Issue by Pierre-vh** [facebookincubator/BOLT#177]
Hello,

While playing with BOLT on aarch64 inputs, I noticed that sometimes the old entry point is called instead of the new one when running with relocations & moving the entry point around.

The reason is that sometimes, in `_start`, compilers generate the following code:

```
   0x0000000000232018 <+24>:	movz	x0, #0x0, lsl #48
   0x000000000023201c <+28>:	movk	x0, #0x0, lsl #32
   0x0000000000232020 <+32>:	movk	x0, #0x21, lsl #16
   0x0000000000232024 <+36>:	movk	x0, #0x7a4
   0x0000000000232028 <+40>:	movz	x3, #0x0, lsl #48
   0x000000000023202c <+44>:	movk	x3, #0x0, lsl #32
   0x0000000000232030 <+48>:	movk	x3, #0x21, lsl #16
   0x0000000000232034 <+52>:	movk	x3, #0x808
   0x0000000000232038 <+56>:	movz	x4, #0x0, lsl #48
   0x000000000023203c <+60>:	movk	x4, #0x0, lsl #32
   0x0000000000232040 <+64>:	movk	x4, #0x21, lsl #16
   0x0000000000232044 <+68>:	movk	x4, #0x888
   0x0000000000232048 <+72>:	bl	0x2108d0 <__libc_start_main@plt>
   0x000000000023204c <+76>:	bl	0x2108e0 <abort@plt>
```

The first four moves are moving the address of `main` into `x0` in fragments, as aarch64 doesn't support operands that large. Those four moves have associated relocations too.
```
00000000002106c8  0000003a0000010d R_AARCH64_MOVW_UABS_G3 00000000002107b4 main + 0
00000000002106cc  0000003a0000010c R_AARCH64_MOVW_UABS_G2_NC 00000000002107b4 main + 0
00000000002106d0  0000003a0000010a R_AARCH64_MOVW_UABS_G1_NC 00000000002107b4 main + 0
00000000002106d4  0000003a00000108 R_AARCH64_MOVW_UABS_G0_NC 00000000002107b4 main + 0
```

However, BOLT doesn't seem to handle those relocations (on master) and thus the optimised executable calls the old entry point in `bolt.org.text`, leading to subtle issues.

Can this be worked around in any way, perhaps with a compiler option? 
Thanks

**Comment by yota9** [comment]
Hello! 
Indeed, currently this relocations are not handled in bolt. Currently I can suggest you to re-compile you binaries with -fPIC -pie flags, it should fix the problem.

**Comment by Pierre-vh** [comment]
Hello,

It seems like it doesn't fully solve the problem, the wrong entry point is still called even when compiling with `-Wl,-q -fpic -pie`.

BOLT takes this branch when processing GOT AArch64 relocations as it "forces" them:
```
      auto Name = Relocation::isGOT(RType) ? "Zero" : SymbolName;
      ReferencedSymbol = BC->registerNameAtAddress(Name, 0, 0, 0);
      SymbolAddress = 0;
      if (Relocation::isGOT(RType))
        Addend = Address;
      DEBUG(dbgs() << "BOLT-DEBUG: forcing relocation against symbol "
                   << SymbolName << " with addend " << Addend << '\n');
```

The output looks like this for the two relocations that apply to `main` in `_start`.
```
BOLT-DEBUG: Relocation: offset = 0x107d0; type = R_AARCH64_ADR_GOT_PAGE; value = 0x20000; symbol = main (); symbol address = 0x20000; addend = 0x0; address = 0x20000; in = _start(*2)
BOLT-DEBUG: registering <absolute>, 0x0, 0 (0x0, 0), data = 0x0, output data = 0x0
BOLT-DEBUG: forcing relocation against symbol main with addend 131072
BOLT-DEBUG: Relocation: offset = 0x107d4; type = R_AARCH64_LD64_GOT_LO12_NC; value = 0xc00; symbol = main (); symbol address = 0xc00; addend = 0x0; address = 0xc00; in = _start(*2)
BOLT-DEBUG: cannot determine referenced section.
```

and in the final executable, the address is still wrong and the old entry point is still called.
Could this be a bug in BOLT?

**Comment by yota9** [comment]
@Pierre-vh Hello!
It is hard for me to say without looking at the objdump. But as far as I understand now the "main" function address is stored at GOT.  The got entry it self has the same address as the original binary, the bolt does not have to patch it. But depending on the dynamic relocations  the address of the main function inside got entry will be handled differently. For example if the got entry has an RELATIVE relocation - it will be patched in patchELFAllocatableRelaSections. 
Sorry if I misunderstand this situation, but again it is hard for me to say something not looking at the binary file :)

**Comment by Pierre-vh** [comment]
Ah, indeed, I was working on master which doesn't have the updated `patchELFAllocatableRelaSections`.
If I use the rebased version it works.
Thanks :)

**Comment by yota9** [comment]
@Pierre-vh I'm glad it works now :)
But I don't think the issue needs no be closed, the problem with AARCH64_MOVW_UABS_G* relocation is still needs to be solved :)

**Comment by yota9** [comment]
@Pierre-vh The relocations are supported now (if it is still actual :))
